config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
  
  resources :posts do
    resources :comments
    post '/rating_plus' => 'application#post_rating_plus'
    post '/rating_minus' => 'application#post_rating_minus'
    post '/add_bookmark' => 'application#add_to_bookmarks'
  end

  resources :images, only: [:create, :destroy, :show]

  resources :users, only: [:show, :edit, :update, :index]

  namespace :admin do
    resources :posts, :users
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :trackable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :confirmable, :validatable

  mount_uploader :avatar, AvatarUploader

  validates :email, presence: true
  validates :username,  presence: true, uniqueness: true

  has_many  :posts
  has_many  :comments
  has_many  :images
  has_many  :post_rating
  has_many  :bookmark

  belongs_to  :role
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :find_user, only: [:show, :edit, :update]

  def index
    @users = User.all
  end

  def edit
    if can_edit_user?
      true
    else
      flash[:error] = "You don't have permission!"
      redirect_to root_path
    end 
  end

  def update
    @user.update_attributes(user_params)

    if @user.errors.empty?
      redirect_to @user
    else
      render "edit"
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :status, :avatar, :fullname, :about)
  end

  def find_user
    @user = User.find(params[:id])
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.haml
%h1= @page_title="Edit profile"
= simple_form_for @user, html:{multipart: true} do |f|
  = f.input :email,   label: false, placeholder: "E-mail"
  = f.input :fullname,  label: false, placeholder: "Fullname"
  = f.input :status,  label: false, placeholder: "Status"
  = f.input :about,  label: false, placeholder: "About"
  = f.file_field :avatar, name: "user[avatar]"
  = f.submit "Save", class: "btn btn-default"

%div#image

app/views/users/show.html.haml
%div.container-fluid
  %div.col-sm-3
    = image_tag @user.avatar
    %p= link_to "Edit profile", edit_user_path if can_edit_profile?
    %p= link_to "New post", new_post_path
  %div.col-sm-8
    %h2= @user.username
    = @user.rating
    %p= @user.status if @user.status
  %div.col-sm-12
    %ul.nav.nav-tabs
      %li.active
        %a{"data-toggle" => "tab", href:"#profile"} Profile
      %li
        %a{"data-toggle" => "tab", href:"#posts"} Posts
      %li
        %a{"data-toggle" => "tab", href: "#comments"} Comments
      %li
        %a{"data-toggle" => "tab", href: "#bookmarks"} Bookmarks
    %div.tab-content
      %div#profile.tab-pane.fade.in.active
        %p= "Fullname: #{@user.fullname}" if @user.fullname?
        %p= "Email: #{@user.email}"
        %p= @user.role.title.capitalize
        %p= @user.about
      %div#posts.tab-pane.fade
        - if @user.posts.count.nonzero?
          - @user.posts.each do |post|
            = link_to post.title, post
            %br
        - else
          %h3 Не добавлено ни одной новости!
      %div#comments.tab-pane.fade
        - if @user.comments.count.nonzero?
          - @user.comments.each do |comment|
            = link_to comment.body, comment.post
            %br
        - else
          %h3 Комментарии отсутствуют!
      %div#bookmarks.tab-pane.fade
        - if @user.bookmark.count.nonzero?
          - @user.bookmark.each do |bookmark|
            = link_to bookmark.post.title, bookmark.post 
            %br