config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
  
  resources :posts do
    resources :comments
    post '/rating_plus' => 'application#post_rating_plus'
    post '/rating_minus' => 'application#post_rating_minus'
    post '/add_bookmark' => 'application#add_to_bookmarks'
  end

  resources :images, only: [:create, :destroy, :show]

  resources :users, only: [:show, :edit, :update, :index]

  namespace :admin do
    resources :posts, :users
  end
  
end

app/models/post.rb
class Post < ApplicationRecord
  require "translit"

  belongs_to  :user
  
  has_many  :images
  has_many  :comments
  has_many  :post_rating
  has_many  :bookmarks

  accepts_nested_attributes_for :images
  validates :title, :body, :user_id, presence: true

  after_create :url_converter

  def url_converter
    if self.url == nil
      self.update_attributes!(url: "#{self.id}-#{Translit.convert(self.title, :english).gsub!(/[^0-9A-Za-z]/, '-')}")
    else
      self.update_attributes!(url: "#{self.id}-#{self.url}")
    end
  end

  def to_param
    "#{self.url}"
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:show, :edit, :update, :destroy, :increment_view]
  before_action :increment_view, only: [:show]

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
    @images = Image.where(user_id: current_user.id, post_id: nil)
  end
 
  def create
    @post = current_user.posts.create(post_params)

    if @post.save
      Image.where(user_id: current_user.id, post_id: nil).update_all(post_id: @post.id)

      if params[:post][:image_ids]
        params[:post][:image_ids].split(" ").each do |id|
          Image.find(id).update_attribute(post_id: @post.id)   
        end
      end
      
      flash[:success] = "Post added!"
      redirect_to @post
    else
      flash.now[:error] = "You have error!"
      render "new"
    end
  end

  def edit
    if can_edit_posts?
      true
    else
      flash[:error] = "You don't have permission!"
      redirect_to root_path
    end 
  end

  def update
    @post.update_attributes(post_params)

    if @post.errors.empty?
      redirect_to @post
    else
      render "edit"
    end
  end

  def destroy
    if can_delete_posts?
      @post.destroy
      redirect_to posts_path
     else
      flash[:error] = "You don't have permission!"
      redirect_to root_path
    end       
  end

  private
  def post_params
    params.require(:post).permit(:title, :body, :source, :image)
  end

  def find_post
    @post = Post.find(params[:id])
  end

  def increment_view
    @post.increment!(:views)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_bbcode.html.haml
%button#bbc{type:"button", value:"b",       onClick:"wrapText('body', '0' )"} b
%button#bbc{type:"button", value:"u",       onClick:"wrapText('body', '1' )"} u
%button#bbc{type:"button", value:"i",       onClick:"wrapText('body', '2' )"} i
%button#bbc{type:"button", value:"img",     onClick:"wrapText('body', '3' )"} Img
%button#bbc{type:"button", value:"s",       onClick:"wrapText('body', '4' )"} s
%button#bbc{type:"button", value:"code",    onClick:"wrapText('body', '5' )"} code
%button#bbc{type:"button", value:"quote",   onClick:"wrapText('body', '6' )"} quote
%button#bbc{type:"button", value:"url",     onClick:"wrapText('body', '7' )"} url
%button#bbc{type:"button", value:"youtube", onClick:"wrapText('body', '8' )"} youtube
%button#bbc{type:"button", value:"gvideo",  onClick:"wrapText('body', '9' )"} gvideo
%button#bbc{type:"button", value:"vimeo",   onClick:"wrapText('body', '10')"} vimeo
%button#bbc{type:"button", value:"email",   onClick:"wrapText('body', '11')"} email
%button#bbc{type:"button", value:"left",    onClick:"wrapText('body', '12')"} left
%button#bbc{type:"button", value:"center",  onClick:"wrapText('body', '13')"} center
%button#bbc{type:"button", value:"right",   onClick:"wrapText('body', '14')"} right
%button#bbc{type:"button", value:"br",      onClick:"wrapText('body', '15')"} br

app/views/posts/_form.html.haml
= f.input :title, label: false, placeholder: "Title"
= render partial: 'bbcode'
= f.input :body, label: false, input_html: {rows: 10, id: "body"}

app/views/posts/_image.html.haml
%div#painting
  = link_to image_tag(@post.images.image.url(:thumb)), @post.image if @post.images 
  %div#name
    = image.title

app/views/posts/_upload.html.haml
= form_for Image.new, url: images_path do |f| 
  = f.label :image, "Upload images:"
  = f.hidden_field :post_id, value: @post.id
  = f.file_field :image, multiple: true, name: "image[image]"

app/views/posts/edit.html.haml
%h1= @page_title="Edit post"
= simple_form_for @post, html:{multipart: true} do |f|
  = render partial: 'form', locals: {f: f}
  = f.submit "Save", class: "btn btn-default"

= render partial: 'upload'

%div#img_thumb
  - @post.images.each do |image|
    = link_to "Удалить", image_path(image), remote: true, method: :delete, data: {confirm: "Уверен?"}
    = image.id
    = link_to image.title.url do  
      = image_tag(image.title.thumb.url)
  
%div#image

app/views/posts/index.html.haml
- @posts.each do |p|
  %br= p.title

app/views/posts/new.html.haml
%h1 Add new post
%section
  = simple_form_for @post, html:{multipart: true} do |f|
    = render partial: 'form', locals: {f: f}
    = f.hidden_field :image_ids, value: nil
    = f.submit "Add"
= render partial: 'upload'

- if @images
  %div#img_thumb
    - @images.each do |image|
      = link_to "Удалить", image_path(image), remote: true, method: :delete, data: {confirm: "Уверен?"}
      = image.id
      = link_to image.title.url do  
        = image_tag(image.title.thumb.url)

%div#image 

app/views/posts/show.html.haml
%h2= @post.title
- if current_user
  %h5.edit
    = link_to "Удалить", post_path(@post), method: :delete, data: {confirm: "Уверн?"} if can_delete_posts?
    = link_to "Редактировать", edit_post_path(@post) if can_edit_posts?
%article= "#{@post.body}".bbcode_to_html.html_safe
%div.info
  %h6
    = fa_icon "user-o", text: "Author: "
    = link_to @post.user.username, @post.user
  %h6= fa_icon "eye", text: "Views: #{@post.views}" 


%div
  = render partial: "comments/new", locals: {post: @post}
  = render partial: "comments/show", locals: {post: @post} 